name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install poetry
          pip install ni-python-styleguide
          poetry install
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run linters
        run: |
          ni-python-styleguide lint ./nidaqmx/
          ni-python-styleguide lint ./nidaqmx_examples/
      - name: Test with pytest
        run: |
          poetry run pytest